name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"   # publish only on version tags like v1.2.3

permissions:
  contents: read
  id-token: write  # REQUIRED for trusted publishing

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/spyprot

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build env
        run: >-
          python3 -m pip install wheel scikit_build
          --user
      - name: Build a binary wheel and a source tarball
        run:
          python3 setup.py bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
